apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: prueba-dummy
    newName: pruebadummyacr.azurecr.io/prueba-dummy
    newTag: latest

patches:
  - path: replica-patch.yaml
